export const QUERYING_QUESTIONS_REQUEST = "QUERYING_QUESTIONS_REQUEST"; // 질문 요청
export const QUERYING_QUESTIONS_SUCCESS = "QUERYING_QUESTIONS_SUCCESS";
export const QUERYING_QUESTIONS_FAILURE = "QUERYING_QUESTIONS_FAILURE";

export const RESET_RESULTS = "RESET_RESULTS";
export const SAVE_RESULTS = "SAVE_RESULTS";

export const CONNECT_SOCKET_REQUEST = "CONNECT_SOCKET_REQUEST"; // 첫 질문 요청
export const CONNECT_SOCKET_SUCCESS = "CONNECT_SOCKET_SUCCESS"; // 첫 질문 성공
export const CONNECT_SOCKET_FAILURE = "CONNECT_SOCKET_FAILURE"; // 첫 질문 실패

export const DISCONNECT_SOCKET = "DISCONNECT_SOCKET";
