export const QUERYING_QUESTIONS_REQUEST = "QUERYING_QUESTIONS_REQUEST"; // 질문 요청
export const QUERYING_QUESTIONS_SUCCESS = "QUERYING_QUESTIONS_SUCCESS";
export const QUERYING_QUESTIONS_FAILURE = "QUERYING_QUESTIONS_FAILURE";

export const QUERYING_FIRST_QUESTION_REQUEST =
  "QUERYING_FIRST_QUESTION_REQUEST"; // 첫 질문 요청
export const QUERYING_FIRST_QUESTION_SUCCESS =
  "QUERYING_FIRST_QUESTION_SUCCESS";
export const QUERYING_FIRST_QUESTION_FAILURE =
  "QUERYING_FIRST_QUESTION_FAILURE";

export const RESET_RESULTS = "RESET_RESULTS";
