export const QUERYING_QUESTIONS_REQUEST = "QUERYING_QUESTIONS_REQUEST"; // 질문 요청
export const QUERYING_QUESTIONS_SUCCESS = "QUERYING_QUESTIONS_SUCCESS";
export const QUERYING_QUESTIONS_FAILURE = "QUERYING_QUESTIONS_FAILURE";
